Working on Working workflow. - 2024-12-04 06:24:28 UTC

diff --git a/.github/workflows/working_linux_build.yml b/.github/workflows/working_linux_build.yml
--- a/.github/workflows/working_linux_build.yml
+++ b/.github/workflows/working_linux_build.yml
@@ -19,17 +19,29 @@ jobs:
         id: working_test_for_source_file_changes
         run: |
           linux_source_files=($(find ./linux/src -type f -iname "*.cpp" -exec basename {} \; -o -iname "*.h" -exec basename {} \;))
+          echo -e "Error:\t" $?
           linux_source_files+=($(find ./linux -maxdepth 1 -type f -iname "makefile" -exec basename {} \; -o -iname "prebuild" -exec basename {} \;))
+          echo -e "Error:\t" $?
           linux_source_files+=($(find ./scripts -maxdepth 1 -type f -iname "*linux*.sh" -exec basename {} \;))
+          echo -e "Error:\t" $?
           printf -v linux_source_files '%s|' ${linux_source_files[*]//\./\\\\.}
+          echo -e "Error:\t" $?
           linux_source_files=${linux_source_files::-1}
+          echo -e "Error:\t" $?
           linux_files=($(eval "git diff --name-only HEAD^ HEAD | grep -E '^.*($linux_source_files)$' --color=never"))
+          echo -e "Error:\t" $?
           linux_files_changed=false
+          echo -e "Error:\t" $?
           if [[ ${#linux_files[@]} -gt 0 ]]; then
+            echo -e "Error:\t" $?  
             linux_files_changed='True'
+            echo -e "Error:\t" $?
           fi
+          echo -e "Error:\t" $?
           echo ${#linux_files[@]}
+          echo -e "Error:\t" $?
           echo "linux_files_changed=$linux_files_changed" >> $GITHUB_OUTPUT
+          echo -e "Error:\t" $?
       - name: Working Linux Build Test
         shell: bash
         if: steps.working_test_for_source_file_changes.outputs.windows_files_changed == 'True'
