Working on Working workflow. - 2024-12-05 00:17:12 UTC

diff --git a/.github/workflows/working_linux_build.yml b/.github/workflows/working_linux_build.yml
--- a/.github/workflows/working_linux_build.yml
+++ b/.github/workflows/working_linux_build.yml
@@ -8,7 +8,7 @@ on:
 
 jobs:
   working_linux_build_test:
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -24,25 +24,25 @@ jobs:
           echo -e "Error:\t" $?
           temp+=($(find ./scripts -maxdepth 1 -type f -iname "*linux*.sh" -exec basename {} \;))
           echo -e "Error:\t" $?
-          printf -v linux_source_files '%s|' ${temp[*]//\./\\\\.}
+          printf -v linux_source_files '%s\\|' "${temp[*]}
           echo -e "Error:\t" $?
           linux_source_files=${linux_source_files::-1}
           echo -e "Error:\t" $?
-          eval echo hey
-# linux_files=($(eval "git diff --name-only HEAD^ HEAD | grep -E '^.*($linux_source_files)$' --color=never"))
-# echo -e "Error:\t" $? 
-# linux_files_changed=false
-# echo -e "Error:\t" $?
-# if [[ ${#linux_files[@]} -gt 0 ]]; then
-#   echo -e "Error:\t" $?  
-#   linux_files_changed='True'
-#   echo -e "Error:\t" $?
-# fi
-# echo -e "Error:\t" $?
-# echo ${#linux_files[@]}
-# echo -e "Error:\t" $?
-# echo "linux_files_changed=$linux_files_changed" >> $GITHUB_OUTPUT
-# echo -e "Error:\t" $?
+          GREP_COMMAND=(grep "$linux_source_files" '--color=never')
+          linux_files=($(git diff --name-only HEAD^ HEAD | "${GREP_COMMAND[@]}"))
+          echo -e "Error:\t" $?
+          linux_files_changed=false
+          echo -e "Error:\t" $?
+          if [[ ${#linux_files[@]} -gt 0 ]]; then
+            echo -e "Error:\t" $?  
+            linux_files_changed='True'
+            echo -e "Error:\t" $?
+          fi
+          echo -e "Error:\t" $?
+          echo ${#linux_files[@]}
+          echo -e "Error:\t" $?
+          echo "linux_files_changed=$linux_files_changed" >> $GITHUB_OUTPUT
+          echo -e "Error:\t" $? 
       - name: Working Linux Build Test
         shell: bash
         if: steps.working_test_for_source_file_changes.outputs.windows_files_changed == 'True'
